nexusdata:
 image: sonatype/nexus:2.11.4-01
 command: echo "data-only container for Nexus"
nexus:
 image: sonatype/nexus:2.11.4-01
 volumes_from:
  - nexusdata
 ports:
  - "9081:8081"
 hostname: "nexus-server"
jenkinsdata:
 build: jenkins-data
jenkins:
 build: jenkins
 volumes_from:
  - jenkinsdata
 volumes:
  - /var/run/docker.sock:/var/run/docker.sock:ro
  - /usr/local/bin/docker:/usr/bin/docker:ro
 ports:
  - "9080:8080"
 privileged: true
 hostname: "jenkins-server"
mavenbuild:
 build: maven-build